[build]
builder = "nixpacks"
buildCommand = "cd backend && go mod tidy && go build -o main . && cd .. && npm ci && npm run build"

[deploy]
startCommand = "./backend/main"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/registro"
healthcheckTimeout = 300

[env]
PORT = "8080"
NODE_ENV = "production"
REACT_APP_API_URL = "${RAILWAY_STATIC_URL}"
MONGO_URI = "${MONGO_URI}"
GIN_MODE = "release"