services:
  - type: web
    name: qrtixpro-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080